[build]
publish="build"
command="""
npm install
npm run build
npm test
"""

[[redirects]]
from = "/installation"
to = "/#installation"

[context.master.environment]
NPM_VERSION = "9"  # Works with Node 14 for this repo.
